/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SizeFinderRouteImport } from './routes/size-finder'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionProductIdRouteImport } from './routes/collection_.$productId'
import { Route as AdminRestockAlertsRouteImport } from './routes/admin.restock-alerts'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order.confirmation.$orderId'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeFinderRoute = SizeFinderRouteImport.update({
  id: '/size-finder',
  path: '/size-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionProductIdRoute = CollectionProductIdRouteImport.update({
  id: '/collection_/$productId',
  path: '/collection/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestockAlertsRoute = AdminRestockAlertsRouteImport.update({
  id: '/restock-alerts',
  path: '/restock-alerts',
  getParentRoute: () => AdminRoute,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order/confirmation/$orderId',
    path: '/order/confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/size-finder': typeof SizeFinderRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/wishlist': typeof WishlistRoute
  '/admin/restock-alerts': typeof AdminRestockAlertsRoute
  '/collection/$productId': typeof CollectionProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/order/confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/size-finder': typeof SizeFinderRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/wishlist': typeof WishlistRoute
  '/admin/restock-alerts': typeof AdminRestockAlertsRoute
  '/collection/$productId': typeof CollectionProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/order/confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/size-finder': typeof SizeFinderRoute
  '/terms': typeof TermsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/wishlist': typeof WishlistRoute
  '/admin/restock-alerts': typeof AdminRestockAlertsRoute
  '/collection_/$productId': typeof CollectionProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/order/confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/cookies'
    | '/forgot-password'
    | '/privacy'
    | '/shipping-returns'
    | '/size-finder'
    | '/terms'
    | '/update-password'
    | '/wishlist'
    | '/admin/restock-alerts'
    | '/collection/$productId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/order/confirmation/$orderId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/cookies'
    | '/forgot-password'
    | '/privacy'
    | '/shipping-returns'
    | '/size-finder'
    | '/terms'
    | '/update-password'
    | '/wishlist'
    | '/admin/restock-alerts'
    | '/collection/$productId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/order/confirmation/$orderId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/cookies'
    | '/forgot-password'
    | '/privacy'
    | '/shipping-returns'
    | '/size-finder'
    | '/terms'
    | '/update-password'
    | '/wishlist'
    | '/admin/restock-alerts'
    | '/collection_/$productId'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/order/confirmation/$orderId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionRoute: typeof CollectionRoute
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  SizeFinderRoute: typeof SizeFinderRoute
  TermsRoute: typeof TermsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  WishlistRoute: typeof WishlistRoute
  CollectionProductIdRoute: typeof CollectionProductIdRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-finder': {
      id: '/size-finder'
      path: '/size-finder'
      fullPath: '/size-finder'
      preLoaderRoute: typeof SizeFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection_/$productId': {
      id: '/collection_/$productId'
      path: '/collection/$productId'
      fullPath: '/collection/$productId'
      preLoaderRoute: typeof CollectionProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restock-alerts': {
      id: '/admin/restock-alerts'
      path: '/restock-alerts'
      fullPath: '/admin/restock-alerts'
      preLoaderRoute: typeof AdminRestockAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order/confirmation/$orderId': {
      id: '/order/confirmation/$orderId'
      path: '/order/confirmation/$orderId'
      fullPath: '/order/confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminRestockAlertsRoute: typeof AdminRestockAlertsRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRestockAlertsRoute: AdminRestockAlertsRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionRoute: CollectionRoute,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  SizeFinderRoute: SizeFinderRoute,
  TermsRoute: TermsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  WishlistRoute: WishlistRoute,
  CollectionProductIdRoute: CollectionProductIdRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
