/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WeddingRouteImport } from './routes/wedding'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as BespokeRouteImport } from './routes/bespoke'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionProductIdRouteImport } from './routes/collection.$productId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingRoute = WeddingRouteImport.update({
  id: '/wedding',
  path: '/wedding',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeRoute = BespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionProductIdRoute = CollectionProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CollectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/bespoke': typeof BespokeRoute
  '/collection': typeof CollectionRouteWithChildren
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$productId': typeof CollectionProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/bespoke': typeof BespokeRoute
  '/collection': typeof CollectionRouteWithChildren
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$productId': typeof CollectionProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/bespoke': typeof BespokeRoute
  '/collection': typeof CollectionRouteWithChildren
  '/wedding': typeof WeddingRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$productId': typeof CollectionProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/bespoke'
    | '/collection'
    | '/wedding'
    | '/wishlist'
    | '/collection/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/bespoke'
    | '/collection'
    | '/wedding'
    | '/wishlist'
    | '/collection/$productId'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/bespoke'
    | '/collection'
    | '/wedding'
    | '/wishlist'
    | '/collection/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  BespokeRoute: typeof BespokeRoute
  CollectionRoute: typeof CollectionRouteWithChildren
  WeddingRoute: typeof WeddingRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding': {
      id: '/wedding'
      path: '/wedding'
      fullPath: '/wedding'
      preLoaderRoute: typeof WeddingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke': {
      id: '/bespoke'
      path: '/bespoke'
      fullPath: '/bespoke'
      preLoaderRoute: typeof BespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$productId': {
      id: '/collection/$productId'
      path: '/$productId'
      fullPath: '/collection/$productId'
      preLoaderRoute: typeof CollectionProductIdRouteImport
      parentRoute: typeof CollectionRoute
    }
  }
}

interface CollectionRouteChildren {
  CollectionProductIdRoute: typeof CollectionProductIdRoute
}

const CollectionRouteChildren: CollectionRouteChildren = {
  CollectionProductIdRoute: CollectionProductIdRoute,
}

const CollectionRouteWithChildren = CollectionRoute._addFileChildren(
  CollectionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  BespokeRoute: BespokeRoute,
  CollectionRoute: CollectionRouteWithChildren,
  WeddingRoute: WeddingRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
